// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://wzwnqtxajmknnnovjtme.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Ind6d25xdHhham1rbm5ub3ZqdG1lIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg5NzUwODAsImV4cCI6MjA2NDU1MTA4MH0.QzTqHPs_iKKpgVurO4T6TtGD4Jn2WuxvuOYZJAT239U";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);